AWSTemplateFormatVersion: 2010-09-09
Description: |
  flask uygulaması ile cloudformationdan instance ayaga kaldırmak.
Parameters:
  KeyName:
    Description: Choose your key pair
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MySecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP. # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bef6cc322bfff646
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData: !Base64 |
        #! /bin/bash
        yum update -y
        yum install python3
        pip3 install flask
        cd /home/ec2-user
        FOLDER="https://raw.githubusercontent.com/Serafettin1905/My_Project_Flask/main/Project-001-Roman-Numerals-Converter/"
        wget ${FOLDER}/app.py
        mkdir templates && cd templates
        wget ${FOLDER}/templates/index.html
        wget ${FOLDER}/templates/result.html
        cd ..
        python3 app.py

Outputs:
  DnsName:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyEc2.PublicDnsName
